name: karate_stars_app
description: Official Karate Stars App written in Flutter for Android and iOS.

version: 2.5.0+34

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: ^4.0.0
  video_player: ^0.10.5
  flutter_parsed_text: ^1.2.3
  webview_flutter: ^0.3.14+1
  share: ^0.6.2+1
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+2
  floor: ^0.9.0
  liquid_pull_to_refresh: ^1.1.1
  cached_network_image: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  floor_generator: ^0.9.0
  build_runner: ^1.7.1
  mock_web_server: ^4.1.1
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stubs/current_news.json
    - assets/stubs/social_news.json
    - assets/credentials.json

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf
    - family: CustomIcons
      fonts:
       - asset: assets/fonts/custom_icons.ttf
