name: karate_stars_app
description: Official Karate Stars App written in Flutter for Android and iOS.

version: 2.6.4+51

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_review: ^2.1.2+1
  cached_network_image: ^3.2.2
  chewie: ^1.3.4
  cupertino_icons: ^1.0.5
  firebase_analytics: ^9.1.7
  firebase_crashlytics: ^2.7.2
  firebase_messaging: ^11.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.4.3+7
  flutter_parsed_text: ^2.2.1
  flutter_secure_storage: ^6.0.0
  flutter_speed_dial: ^6.0.0
  get_it: ^7.2.0
  google_mobile_ads: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  line_icons: ^2.0.1
  liquid_pull_to_refresh: ^3.0.1
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.3+1
  purchases_flutter: ^4.3.0
  settings_ui: ^2.0.2
  share_plus: ^4.1.0
  shared_preferences: ^2.0.15
  video_player: ^2.4.7
  visibility_detector: ^0.3.3
  youtube_player_flutter: ^8.1.0
dev_dependencies:
  build_runner: ^2.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mock_web_server: ^5.0.0-nullsafety.1
  mocktail: ^0.3.0
  test: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stubs/current_news.json
    - assets/stubs/social_news.json
    - .env.development
    - .env.production

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
