name: karate_stars_app
description: Official Karate Stars App written in Flutter for Android and iOS.

version: 2.5.0+34

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.3.1
  firebase_messaging: ^10.0.6
  floor: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.3.2
  flutter_parsed_text: ^2.2.1
  flutter_secure_storage: ^4.2.1
  flutter_speed_dial: ^4.4.0+2
  get_it: ^7.2.0
  google_mobile_ads: ^1.0.0
  http: ^0.13.3
  line_icons: ^2.0.1
  liquid_pull_to_refresh: ^3.0.0
  overlay_support: ^1.2.1
  share: ^2.0.4
  shared_preferences: ^2.0.8
  video_player: ^2.1.15
  youtube_player_flutter: ^8.0.0
dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mock_web_server: ^5.0.0-nullsafety.1
  mocktail: ^0.1.4
  test: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stubs/current_news.json
    - assets/stubs/social_news.json
    - .env

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
