name: karate_stars_app
description: Official Karate Stars App written in Flutter for Android and iOS.

version: 2.5.0+38

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  chewie: ^1.3.2
  cupertino_icons: ^1.0.4
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.4.3+4
  flutter_parsed_text: ^2.2.1
  flutter_secure_storage: ^5.0.2
  flutter_speed_dial: ^5.0.0+1
  get_it: ^7.2.0
  google_mobile_ads: ^1.1.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  line_icons: ^2.0.1
  liquid_pull_to_refresh: ^3.0.1
  overlay_support: ^1.2.1
  package_info_plus: ^1.4.0
  settings_ui: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.13
  video_player: ^2.4.0
  visibility_detector: ^0.2.2
  youtube_player_flutter: ^8.0.0
dev_dependencies:
  build_runner: ^2.1.7
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  mock_web_server: ^5.0.0-nullsafety.1
  mocktail: ^0.3.0
  test: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stubs/current_news.json
    - assets/stubs/social_news.json
    - .env.development
    - .env.production

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
