/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const fontFamily = 'CustomIcons';

  static const IconData twitter = IconData(0xf099, fontFamily: fontFamily);
  static const IconData facebook = IconData(0xf09a, fontFamily: fontFamily);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: fontFamily);
  static const IconData instagram = IconData(0xf16d, fontFamily: fontFamily);
}
